[package]
name = "findr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.8", features = ["derive"] }
walkdir = "2.5.0"
regex = "1.10.5"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
tempfile = "3.10.1"
pretty_assertions = "1.4.0"
